name: healthcaredecision
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_speed_dial: ^1.2.1
  flutter_dialogflow: ^0.1.3
  folding_cell: "^0.1.2"

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:



  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/precaution1.gif
     - assets/images/precaution2.gif
     - assets/images/precaution3.gif
     - assets/images/precaution4.gif
     - assets/images/precaution5.gif
     - assets/images/precaution6.gif
     - assets/images/precaution7.gif
     - assets/images/heartfunction.gif
     - assets/images/smoking.png
     - assets/images/working.png
     - assets/images/fruits.png
     - assets/images/weight.png
     - assets/images/stress.png
     - assets/images/screening.png
     - assets/images/sleep.png
     - assets/images/function.png
     - assets/images/diagnosis.png
     - assets/images/more1.gif
     - assets/images/chest.png
     - assets/images/chestxray.gif
     - assets/images/stresstest.png
     - assets/images/stresstest.gif
     - assets/images/endotest.gif
     - assets/images/endo.png
     - assets/images/card.png
     - assets/images/Doctor.png
     - assets/images/docIcon.png
     - assets/images/heart-beating.gif
     - assets/doctor-cqfxkd-247966848f36.json
     - assets/images/mobile_doctor.png







  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        -  asset: assets/Poppins-SemiBold.ttf


  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
